### ISSUE TITLE
有报错，帮忙看一下

### ISSUE THREAD

**Issue by tangyujing-327** [yijinc/taropui#1]
import Drag from "@fishui/uni-app/lib/Drag/index.vue";

in ./node_modules/@fishui/uni-app/lib/Drag/index.vue?vue&type=template&id=24a5a754&

Syntax Error: Unexpected token, expected "," (10:25)

**Comment by yijinc** [comment]
你尝试下 取消勾选【将 JS 编译成 ES5】

![image](https://user-images.githubusercontent.com/8774441/228773285-916151bf-4963-4c54-abb2-7e4344d0c6c2.png)

**Comment by tangyujing-327** [comment]
取消勾选 很多es6语法编译后直接报错了

**Comment by yijinc** [comment]
不会呀，一般不是原生小程序开发，建议都不勾选这个的

**Comment by xiumark** [comment]
示例效果和代码中切换效果不一样，是不是代码不一致？
