### ISSUE TITLE
Drag uni-app 版本是否支持 vue2 版本

### ISSUE THREAD

**Issue by soarotech** [yijinc/taropui#3]
您好，我想问一下，下面的插件是否支持  uni-app 开发的vue2版本，因为我现在创建的版本的 vue2 的

(https://github.com/yijinc/fishui/tree/master/packages/uni-app/src/components/Drag)

**Comment by yijinc** [comment]
不支持，目前开发是用vue3 api实现的。如需支持 请直接将组件源码 api 换成 vue2即可
